iai_qb_cube_driver:
  joint_names:
    - arm_1_joint
    - arm_2_joint
    - arm_3_joint
    - arm_4_joint
  arm_1_joint:
    id: 1
  arm_2_joint:
    id: 2
  arm_3_joint:
    id: 3
  arm_4_joint:
    id: 4
  publish_frequency: 50.0
  port: /dev/ttyUSB0
